// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2V0qLlkLyil8frtJG1-h-9zWX8sS5QQo',
    appId: '1:892792820573:web:07623f2e79f8a6131cceb4',
    messagingSenderId: '892792820573',
    projectId: 'realtime-quiz-mermer',
    authDomain: 'realtime-quiz-mermer.firebaseapp.com',
    databaseURL: 'https://realtime-quiz-mermer-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'realtime-quiz-mermer.appspot.com',
    measurementId: 'G-PHKQ2BL5YX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAy3o00_NvrNBwfQNNrQU-ekSgUvGnqEO8',
    appId: '1:892792820573:android:aabe24bdeb5b0c0f1cceb4',
    messagingSenderId: '892792820573',
    projectId: 'realtime-quiz-mermer',
    databaseURL: 'https://realtime-quiz-mermer-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'realtime-quiz-mermer.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlp0azDl_VY0i5vgqkINxekG8CzayW2sA',
    appId: '1:892792820573:ios:5d7c7c7a41bc83081cceb4',
    messagingSenderId: '892792820573',
    projectId: 'realtime-quiz-mermer',
    databaseURL: 'https://realtime-quiz-mermer-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'realtime-quiz-mermer.appspot.com',
    iosBundleId: 'com.mermer.realtimeQuizApp',
  );
}
